development:
  cloud_name: dvfwz9gre
  api_key: '689175426135985'
  api_secret: qjZHRQ_IeQ5Vk3yU9jZ7z1K3qWk
  enhance_image_tag: true
  static_image_support: false
production:
  cloud_name: dvfwz9gre
  api_key: '689175426135985'
  api_secret: qjZHRQ_IeQ5Vk3yU9jZ7z1K3qWk
  enhance_image_tag: true
  static_image_support: true
test:
  cloud_name: dvfwz9gre
  api_key: '689175426135985'
  api_secret: qjZHRQ_IeQ5Vk3yU9jZ7z1K3qWk
  enhance_image_tag: true
  static_image_support: false
